# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fe8eb8d94529e2a82cde198ff2f601c1edc2d76e2c362482f51ef38cb6672723bd84e68e25e587ffc23b364862835f0e4d9811ddbf4fb0916e121dd7d1ed4e0

test:
  secret_key_base: e15a21a044e7967e984d2b206a3541acecbca6d444c1dd901b43dc8d588dafb28d33ac78491999687b5d17ce18b52dc8406a95b0d5771f80c54aba7f6acdf52a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
